import Head from 'next/head'
import Image from 'next/image'
import Intro from '../components/Intro/Intro'
import styles from '../styles/Home.module.css'
import Product from '../components/Product/Product'
import demaquilante from '../assets/images/demaquilante.png'
import HomeScroll from '../components/HomeScroll/HomeScroll'
import Soap from '../components/Soap/Soap'
const description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."



export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeScroll/>
      <Intro />

      <Soap/>


      {/* <section id="demaquilante">
        <Product
          title="Demaquilante"
          description={description}
          image={demaquilante.src}
          video="https://suscidadao.000webhostapp.com/product-video.webm"
          goTo="demaquilante"
          align="left"
        />
      </section>
      */}


      <section id="sabonete">
        <Product
          title="Sabonete"
          description={description}
          image={demaquilante.src}
          video="https://suscidadao.000webhostapp.com/sabonete.webm"
          goTo="demaquilante"
        />
      </section>
    </div>
  )
}
